version: "3"

services:
  localhost:
    build: ./pkg
    restart: always
    container_name: postgres
    volumes:
      - ./localhost:/var/lib/postgresql/data
    ports:
      - 5432:5432
  snippetbox:
    build: .
    depends_on:
      - localhost
    restart: always
    container_name: gosnippet
    ports:
      - 4000:4000